name: 部署文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false  # 如果不使用子模块，这里设置为 false

      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:build

      
      - name: 部署文档到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          # 如果你想让 gh-pages 分支成为一个孤立的分支，可以添加以下选项
          # force_orphan: true

      - name: 设置 SSH 环境
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H yzyx.fun >> ~/.ssh/known_hosts
          echo "Host yzyx.fun
          StrictHostKeyChecking no" >> ~/.ssh/config
          
      - name: Set SSH key file permissions
        run: chmod 600 /home/runner/.ssh/id_rsa

      - name: 测试 SSH 连接
        run: ssh -T git@github.com

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: yzyx.fun 
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
           cd /www/wwwroot/www.yzyx.fun/blogs
           git pull origin gh-pages  # 拉取最新的代码